version: '3.9'

services:
  http:
    build:
      context: .
      dockerfile: docker/Dockerfile.http
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: ${DATABASE_URL}

  ws:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - redis
    environment:
      Redisprocess: redis://redis:6379
      kafkaprocess: kafka:9092

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    restart: always
