version: '3.9'

services:
  http:
    build:
      context: .
      dockerfile: docker/Dockerfile.http
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: ${DATABASE_URL}

  ws:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - redis
    environment:
      REDIS_URL: redis://redis:6379
      KAFKA_BROKER: kafka:9092

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379" # 🔁 Redis port mapped to host for access

  zookeeper:
    image: bitnami/zookeeper:latest
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'

  kafka:
    image: bitnami/kafka:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    depends_on:
      - zookeeper
