version: '3.9'
services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.web
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - http

  http:
    build:
      context: .
      dockerfile: docker/Dockerfile.http
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: ${DATABASE_URL}

  ws:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - redis
    environment:
      REDIS_URL: redis://redis:6379
      KAFKA_BROKER: kafka:9092

  redis:
    image: redis:7-alpine
    

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
