name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push WS Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.ws
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/canvacraft-ws:${{ github.sha }}

      - name: Build and push HTTP Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.http
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/canvacraft-http:${{ github.sha }}

      - name: SSH and deploy via docker-compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_OS }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/ubuntu/Webrtcteachingplatform
            git pull origin main
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            echo "WS_IMAGE_TAG=${{ github.sha }}" > .env
            echo "HTTP_IMAGE_TAG=${{ github.sha }}" >> .env

            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --build
